### ISSUE TITLE
fails in chrome

### ISSUE THREAD

**Issue by abrown28** [Doist/ScriptCommunicator#2]
Linux Chrome 6.0.472.63

It uses the document.writeln function but nothing gets pushed into the dom.

**Comment by amix** [comment]
Does not fail in Chrome.

**Comment by abrown28** [comment]
did you try linux chrome? I tried a different method of injecting the script tag into the dom and discovered that if you insert a script tag with a src attribute it will be parsed after a script tag without a src attribute. anyways thanks for the code. it's taught me a lot :)

**Comment by amix** [comment]
Did not try Linux Chrome, but would love if you could debug this more - or even better: provide a patch :)
